server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.118.100:1111  # 换成nginx的1111端口，做集群
      #server-addr: localhost:8848


#动态刷新配置 , 需暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'