server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gourd-baby/springcloud-config.git  #GitHub上面的git仓库路径
          search-paths:   #搜索目录
            - springcloud-config  #GitHub上面的git仓库名字
          default-label: main   #该仓库上面的分支
  rabbitmq:
    host: redis100
    port: 5672
    username: admin
    password: 123

#rabbitmq相关配置

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

###rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
