server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的id，唯一标识
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行断言

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
            - After=2023-04-26T20:08:35.143+08:00[Asia/Shanghai]
            - Before=2023-04-27T20:13:35.143+08:00[Asia/Shanghai]
            #- Cookie=username,crj

      discovery:
        locator:
          enabled: true



eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true #注册进eureka服务注册中心
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
